#!/usr/bin/env bash
set -euo pipefail

PIPER_PLUS_VERSION="${PIPER_PLUS_VERSION:-v1.12.0}"
MODEL_REPO="${MODEL_REPO:-ayousanz/piper-plus-tsukuyomi-chan}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PIPER_DIR="$ROOT_DIR/_piper"
MODEL_DIR="$ROOT_DIR/models"

mkdir -p "$PIPER_DIR" "$MODEL_DIR" "$ROOT_DIR/tools"

uname_s="$(uname -s)"
uname_m="$(uname -m)"

case "$uname_s:$uname_m" in
  Linux:x86_64)
    asset="piper-plus-cli-linux-x64.tar.gz"
    ;;
  Linux:aarch64|Linux:arm64)
    asset="piper-plus-cli-linux-arm64.tar.gz"
    ;;
  Linux:armv7*|Linux:armv6*)
    asset="piper-linux-armv7.tar.gz"
    ;;
  Darwin:arm64)
    asset="piper-plus-cli-osx-arm64.tar.gz"
    ;;
  Darwin:x86_64)
    asset="piper-plus-cli-osx-x64.tar.gz"
    ;;
  *)
    echo "Unsupported platform: $uname_s $uname_m" >&2
    exit 1
    ;;
esac

archive="$PIPER_DIR/$asset"
url="https://github.com/ayutaz/piper-plus/releases/download/$PIPER_PLUS_VERSION/$asset"

echo "Downloading $url"
curl -L "$url" -o "$archive"
tar -xzf "$archive" -C "$PIPER_DIR"

cli="$(find "$PIPER_DIR" -type f \( -name 'PiperPlus.Cli' -o -name 'piper' \) | head -1)"
chmod +x "$cli"

cat > "$ROOT_DIR/tools/piper" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by setup_piper.sh. The bridge calls _piper/PiperPlus.Cli
# directly, but this wrapper is useful for quick manual synthesis.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
BIN="$HERE/../_piper/PiperPlus.Cli"
if [ ! -x "$BIN" ]; then
  echo "PiperPlus.Cli not found: $BIN" >&2
  exit 1
fi
exec "$BIN" "$@"
EOF
chmod +x "$ROOT_DIR/tools/piper"

echo "Downloading Tsukuyomi model metadata"
curl -L "https://huggingface.co/$MODEL_REPO/resolve/main/config.json" -o "$MODEL_DIR/config.json"

if [ ! -f "$MODEL_DIR/tsukuyomi-chan-6lang-fp16.onnx" ]; then
  curl -L "https://huggingface.co/$MODEL_REPO/resolve/main/tsukuyomi-chan-6lang-fp16.onnx" \
    -o "$MODEL_DIR/tsukuyomi-chan-6lang-fp16.onnx"
fi

echo "piper installed:"
echo "  bin: $ROOT_DIR/tools/piper"
echo "  model: $MODEL_DIR/tsukuyomi-chan-6lang-fp16.onnx"
echo "  default bin: tools/piper"
echo "  default model: models/tsukuyomi-chan-6lang-fp16.onnx"
